# Generated by Django 5.1 on 2024-09-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('microgreen_type', models.CharField(max_length=255)),
                ('microgreen_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimatedTime', models.DurationField()),
            ],
        ),
    ]
